[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = "true"

[tasks.run]
command = "cargo"
args = ["run"]
env = { "RUSTFLAGS" = "-Awarnings", "RUST_LOG" = "debug" }
watch = true

[tasks.release]
run_task = { name = ["build-release"], parallel = true }

[tasks.format]
command = "cargo"
args = ["clippy", "--fix", "--allow-dirty"]

[tasks.lint]
command = "cargo"
args = ["clippy"]

[tasks.start]
run_task = { name = ["run"], fork = true, parallel = true }
# workspace = false
