[package]
name = "ms_calendar"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "jvp-ms-calendar"
path = "src/main.rs"

[dependencies]
common = { workspace = true }
